title: Default Page

tabs:
  general:
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              text_content:
                label: Content
                type: textarea
                size: large
                font: monospace
              text:
                type: textarea
                size: large
      sidebar:
        width: 1/3
        sections:
          files:
            type: files
            label: Assets
            batch: true
  seo: tabs/seo
